// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     // ignore: missing_enum_constant_in_switch
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//     }

//     throw UnsupportedError(
//       'DefaultFirebaseOptions are not supported for this platform.',
//     );
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyD5IlojmS8xC3tOnJmNcFbfZ34ePl4cMVs',
//     appId: '1:77584886550:web:b6ba7f280fca7b03bafe37',
//     messagingSenderId: '77584886550',
//     projectId: 'storytrap-40b82',
//     authDomain: 'storytrap-40b82.firebaseapp.com',
//     storageBucket: 'storytrap-40b82.appspot.com',
//     measurementId: 'G-XBEBF783CH',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDSI4NnIXAt9Zsq97jC-N4qgBnnVfgH-m8',
//     appId: '1:77584886550:android:9b8c6d9e187d41ebbafe37',
//     messagingSenderId: '77584886550',
//     projectId: 'storytrap-40b82',
//     storageBucket: 'storytrap-40b82.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCV5vKTMmPJyRc9U-h-ePkuFJ4o9tE8l9Y',
//     appId: '1:77584886550:ios:c30ca99852447273bafe37',
//     messagingSenderId: '77584886550',
//     projectId: 'storytrap-40b82',
//     storageBucket: 'storytrap-40b82.appspot.com',
//     androidClientId: '77584886550-0c66k479bsnndv13dhgeruierhnatjtp.apps.googleusercontent.com',
//     iosClientId: '77584886550-uj04j6r78rh17a1na4udksdetpglp7oi.apps.googleusercontent.com',
//     iosBundleId: 'com.journalpost.storytrapapp',
//   );
// }
